name: CI

on: [push]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git submodule update --init --recursive
        nuget restore de4dot.sln
        msbuild de4dot.sln /p:Configuration=Release /m /verbosity:normal /p:WarningLevel=0
    - name: Create ZIP
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        Compress-Archive -Path Release/* -DestinationPath de4dot-cex
      
    - uses: actions/upload-artifact@v1
      with:
        name: de4dot-net35
        path: '*.zip'
